port = 3000
allowed_origin = "http://localhost:3001"
client_url = "http://localhost:3001"
session_expiration_in_days = 30
ssl = false

[scylla]
hosts = ["127.0.0.1:9042", "127.0.0.1:9043", "127.0.0.1:9044"]
keyspace = "nodecosmos"
username = ""
password = ""

[redis]
host = "127.0.0.1:6379"
url = "redis://127.0.0.1:6379/"

[elasticsearch]
host = "http://127.0.0.1:9200"

[aws]
bucket = "nodecosmos-development"
