port = 3000
allowed_origin = "http://localhost:3001"
secret_key = "aSx1aUVGmXkw1moGEVwkq2o7WXsaU6P0kzYbsuDMXLc=zeljazeljazeljazelja"
session_expiration_in_days = 30

[scylla]
hosts = ["127.0.0.1:9042", "127.0.0.1:9043", "127.0.0.1:9044"]
keyspace = "nodecosmos"

[redis]
host = "127.0.0.1:6379"
