port = 3000
allowed_origin_1 = "http://localhost:3001"
allowed_origin_2 = "http://192.168.1.106:3001"
client_url = "http://localhost:3001"
session_expiration_in_days = 30
ssl = false

[scylla]
hosts = ["127.0.0.1:9042", "127.0.0.1:9043", "127.0.0.1:9044"]
keyspace = "nodecosmos"

[redis]
urls = ["redis://127.0.0.1:6379/"]
instances = 1

[elasticsearch]
hosts = ["http://127.0.0.1:9200"]

[aws]
bucket = "nodecosmos-development"

#[smtp]
#starttls = true
#host = ""
#port = 587
#username = ""
#password = ""
#from_name = ""
#from_email = ""
