[package]
name = "nodecosmos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
futures = "0.3.30"
scylla = "0.12.0"
tokio = { version = "1.37.0", features = ["full"] }
tokio-stream = { version = "0.1.15", features = ["sync"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
toml = "0.8.12"
chrono = "0.4.37"
actix-web = { version = "4.5.1", features = ["cookies"] }
actix-session = { version = "0.9.0", features = ["redis-actor-session"] }
actix-cors = "0.7.0"
actix-multipart = "0.6.1"
env_logger = "0.11.3"
bcrypt = "0.15.1"
colored = "2.1.0"
ammonia = "4.0.0"
elasticsearch = "8.5.0-alpha.1"
deadpool-redis = "0.15.0"
aws-config = "1.1.9"
aws-sdk-s3 = "1.21.0"
image = "0.25.1"
mozjpeg = "0.10.7"
actix-web-actors = "4.3.0"
actix = "0.13.3"
dashmap = "5.5.3"
bytestring = "1.3.1"
charybdis = "0.4.11"
yrs = "0.18.2"
base64 = "0.22.0"
uuid = "1.8.0"
quick-xml = "0.31.0"
log = "0.4"
nodecosmos-macros = { path = "../nodecosmos-macros" }
strum = "0.26"
strum_macros = "0.26"

