[package]
name = "nodecosmos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
charybdis = { path = "../charybdis" }
charybdis_macros = { path = "../charybdis_macros" }
dotenv = "0.15.0"
futures = "0.3.28"
scylla = "0.8.0"
tokio = { version = "1.27.0", features = ["full"] }
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
toml = "0.7.3"
chrono = "0.4.24"
actix-web = "4.3.1"
