[package]
name = "nodecosmos-macros"
edition = "2021"
description = "Proc macros for the nodecosmos project"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.64"
syn = { version = "2.0.10", features = ["full"] }
quote = "1.0.26"
log = "0.4.21"
